version: '3.3'
services:
  db:
    container_name: database
    ports:
      - 5432:5432
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always

  web:
    container_name: server
    build:
      context: .
    volumes:
      - /root/my-deployment:/src
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

#  api:
#    container_name: api
#    build: .
#    volumes:
#      - .:/src
#    command: python manage.py app
#    restart: always

