version: "3.7"

services:
  db:
    container_name: database
    ports:
      - 5432:5432
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      cache_from:
        - docker.pkg.github.com/sharunovevgeny/apifortestci-cd/api:latest
    image: docker.pkg.github.com/sharunovevgeny/apifortestci-cd/api:latest
    volumes:
      - /root/my-deployment:/src
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    depends_on:
      - db
    restart: always
