name: TestCICD

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: 
      - main

jobs:
  my_test:
    name: HelloTest
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run : echo "Hello World from Deploy"
  my_deploy:
    name: HelloDeploy
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run : echo "Hello World from Deploy"
    
  
