name: TestCICD
env:
  APPLICATIONS_NAME: "MyDjango"
  DEPLOY_PACKAGE_NAME: "dgango-deploy-ver-${{ github.sha }}"

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: 
      - main

jobs:
  my_test:
    name: HelloTest
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello MessageTEst
        run : echo "Hello World from TEst"
        
      - name: Execure few commands
        run: |
          echo "Hello Message1"
          echo "Hellow Message2"
          echo "Applications name: ${{ env.APPLICATIONS_NAME }}"
      - name: Git clone my repo
        uses: actions/checkout@v1
      - name: Check folder
        run: ls -la
  my_deploy:
    name: HelloDeploy
    runs-on: ubuntu-latest
    needs: [my_test]
    steps:
      - name: Print Hello Message
        run : echo "Hello World from Deploy"
        
      - name: Execure few commands
        run: |
          echo "Hello Message1"
          echo "Hellow Message2"
          echo "Applications name: ${{ env.DEPLOY_PACKAGE_NAME }}"
    
  
