name: TestCICD
env:
  APPLICATIONS_NAME: "MyDjango"
  DEPLOY_PACKAGE_NAME: "dgango-deploy-ver-${{ github.sha }}"

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: 
      - main

jobs:
  my_test:
    name: HelloTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: "test"
        run: |
          mkdir -p "$HOME/.ssh"
          printf '%s\n' "${{ secrets.DOCKER_SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          eval $(ssh-agent)
          ssh-add "$HOME/.ssh/id_rsa"
          echo "Add known hossts"
          sudo printf '%s %s\n' "root@45.144.64.69" "${{ secrets.DOCKER_SSH_PUBLIC_KEY }}" > sudo /etc/ssh/ssh_known_hosts
          ssh -q -t -i "$HOME/.ssh/id_rsa" \
              -o UserKnownHostsFile=/dev/null \
              -o StrictHostKeyChecking=no root@45.144.64.69
      - name: Print Hellosft
        run : |
          echo "dса"
