name: TestCICD
env:
  APPLICATIONS_NAME: "MyDjango"
  DEPLOY_PACKAGE_NAME: "dgango-deploy-ver-${{ github.sha }}"

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: 
      - main

jobs:
  my_test:
    name: HelloTest
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Messadwddddgrgfgfdvfsfdft
        run : |
          echo "dfdfdfddgffgfsfd"
          ssh-keygen -f "/etc/ssh/ssh_known_hosts" -R 45.144.64.69
        
      - name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@45.144.64.69
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          deploy_path: /root/my-deployment
          args: up -d
          pre_deployment_command_args: 'bundle exec rake db:migrate'
          docker_prune: 'true'
          pull_images_first: 'true'
    
  
