name: TestCICD
env:
  APPLICATIONS_NAME: "MyDjango"
  DEPLOY_PACKAGE_NAME: "dgango-deploy-ver-${{ github.sha }}"

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: 
      - main

jobs:
  my_test:
    name: HelloTest
    runs-on: ubuntu-latest
    steps:
      - name: "Tds"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOCKER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.DOCKER_SSH_PUBLIC_KEY }}" > ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa root@45.144.64.69 -tt "echo test > testfile1"
          ssh -i ~/.ssh/id_rsa root@45.144.64.69 -tt "echo test > testfile1"
          ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
          cat ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa.pub
          ls ~/.ssh/
          
      - name: Print Hello Messadwddddgrffgfgfdvfsfdft
        run : |
          echo "dfdfdfddgffgfsffggdfdса"
      - name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: root@45.144.64.69
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ~/.ssh/id_rsa.pub
          deployment_mode: docker-compose
          deploy_path: /root/my-deployment
          args: up -d
          pre_deployment_command_args: 'bundle exec rake db:migrate'
          docker_prune: 'true'
          pull_images_first: 'true'
  my_tweest:
    name: HelloTest2
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Messadwddddgrgfgfdvfsfdft
        run : sudo cat /etc/ssh/ssh_known_hosts
    
  
