name: TestCICD

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: 
      - main

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Log in to GitHub Packages
        run: docker login docker.pkg.github.com -u SharunovEvgeny -p ${{ secrets.GITHUB_TOKEN }}
      - name: Pull images
        run: docker push docker.pkg.github.com/sharunovevgeny/apifortestci-cd/api:latest|| true
      - name: Build images
        run: docker-compose -f docker-compose.ci.yml build
      - name: Push images
        run: docker push docker.pkg.github.com/sharunovevgeny/apifortestci-cd/api:latest
     
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: "deploy"
        run: |
          mkdir -p "$HOME/.ssh"
          printf '%s\n' "${{ secrets.DOCKER_SSH_PRIVATE_KEY }}" > "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"
          eval $(ssh-agent)
          ssh-add "$HOME/.ssh/id_rsa"
          echo "Add known hossts"
          sudo printf '%s %s\n' "root@45.144.64.69" "${{ secrets.DOCKER_SSH_PUBLIC_KEY }}" > sudo /etc/ssh/ssh_known_hosts
          scp  -i "$HOME/.ssh/id_rsa" -o StrictHostKeyChecking=no -r ./docker-compose.prod.yml root@45.144.64.69:/root/my-deployment/docker-compose.prod.yml
          ssh -q -t -i "$HOME/.ssh/id_rsa" \
              -o UserKnownHostsFile=/dev/null \
              -o StrictHostKeyChecking=no root@45.144.64.69 << 'ENDSSH'
          cd /root/my-deployment/
          docker login docker.pkg.github.com -u SharunovEvgeny -p ${{ secrets.GITHUB_TOKEN }}
          docker pull docker.pkg.github.com/sharunovevgeny/apifortestci-cd/api:latest
          docker-compose -f docker-compose.prod.yml up -d
          ENDSSH
